environment: development
version: 0.1.0
title: Bootstragram Theme
description: >
  Bootstragram's awesome Jekyll theme.

menu:
  item0:
    title: Link 1
    path: '#about1'
  item1:
    title: Link 2
    path: '#about2'
  item2:
    title: Link 3
    path: '#about3'

submenu:
  item0:
    title: Sub-Link 1
    path: '#about1'
  item1:
    title: Sub-Link 2
    path: '#about2'
  item2:
    title: Sub-Link 3
    path: '#about3'
